### PR TITLE
added settings toggle to exclude empty topics

### PR DESCRIPTION
**Pull request by t-schroeder**
Pull Request for #5

### CODE REVIEW

**Comment by goggo24** [comment]
Thanks for providing a pull request. We will have a look and accept it, if it's fine in our next version ;)

**Comment by ndunand** [comment]
@goggo24 will there be a minor version release including this, or would this be in the next major version, i.e. for Moodle 3.8?

**Comment by goggo24** [comment]
We are already working on v.3.8.0 - I don't know if we can manage it to include it in the major, but definitely in the next minor. Greetings from Vienna, Eva

**Comment by goggo24** [comment]
Included in v.3.9.0. - adminsetting to exclude empty topics (default: no) - coming in the next days!

**Pull request closed without merging**
